import React, { useEffect, useState } from 'react';
import { useQueries } from '@tanstack/react-query';
import { getDocs, collection } from 'firebase/firestore';
import type { NextPage } from 'next';
import Head from 'next/head';
import { PerformanceBarChart, StocksOverview } from '../components';
import { database } from '../config/firebase';
import { useAuth } from '../hooks';

type StoredStock = {
  name: string;
  ticker: string;
};

const getFinanceChart = async (ticker: string) => {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_CORS_PROXY}https://query1.finance.yahoo.com/v8/finance/chart/${ticker}?interval=1d&range=1y`
  );

  if (!response.ok) {
    throw new Error('Oops an error occurred!');
  }

  return response.json();
};

const getStocksFromFirestore = async (userId: string): Promise<StoredStock[]> => {
  const querySnapshot = await getDocs(collection(database, `users/${userId}/stocks`));

  return querySnapshot.docs.map((doc) => {
    // doc.data() is never undefined for query doc snapshots
    return doc.data() as StoredStock;
  });
};

const Home: NextPage = () => {
  const { user } = useAuth();
  const [stocks, setStocks] = useState<StoredStock[]>([]);
  const [isLoadingStocks, setIsLoadingStocks] = useState(false);
  const [successfullyLoadedStocks, setSuccessfullyLoadedStocks] = useState(false);

  useEffect(() => {
    if (user?.uid) {
      const getStocks = async () => {
        setIsLoadingStocks(true);

        try {
          const stocksFromFirestore = await getStocksFromFirestore(user?.uid);
          setSuccessfullyLoadedStocks(true);
          setStocks(stocksFromFirestore);
        } catch (e) {
          console.error('error:', e);
        }

        setIsLoadingStocks(false);
      };

      void getStocks();

      // setDoc(doc(database, `users/${user?.uid}/stocks`, 'ABBV.VI'), {
      //   name: 'AbbVie',
      //   ticker: 'ABBV.VI'
      // });
      // setDoc(doc(database, `users/${user?.uid}/stocks`, 'ALV.DE'), {
      //   name: 'Allianz',
      //   ticker: 'ALV.DE'
      // });
      // setDoc(doc(database, `users/${user?.uid}/stocks`, 'BAS.DE'), {
      //   name: 'BASF',
      //   ticker: 'BAS.DE'
      // });
      // setDoc(doc(database, `users/${user?.uid}/stocks`, 'BMT.DE'), {
      //   name: 'British American Tobacco',
      //   ticker: 'BMT.DE'
      // });
      // setDoc(doc(database, `users/${user?.uid}/stocks`, 'SRB.F'), {
      //   name: 'Starbucks',
      //   ticker: 'SRB.F'
      // });
    }
  }, [user?.uid]);

  const stockQueries = useQueries({
    queries: stocks.map((stock) => {
      return {
        queryKey: ['stocks', stock.ticker],
        placeholderData: { ...stock },
        queryFn: () => getFinanceChart(stock.ticker),
        staleTime: 1000 * 60 * 15,
        cacheTime: 1000 * 60 * 15,
        select: (data) => ({
          ticker: stock.ticker,
          name: stock.name,
          price: data.chart?.result[0].meta.regularMarketPrice
        })
      };
    })
  });

  console.log('stockQueries:', stockQueries);

  return (
    <>
      <Head>
        <title>Dip Finder</title>

        <meta name="description" content="Generated by create next app" />
      </Head>
      <>
        <StocksOverview
          isLoading={isLoadingStocks}
          successfullyLoaded={successfullyLoadedStocks}
          queries={stockQueries}
        />
        <PerformanceBarChart stocks={[]} />
      </>
    </>
  );
};

export default Home;
