import React, { useEffect, useState } from 'react';
import { getAuth, signOut } from 'firebase/auth';
import { doc, getDoc, setDoc, DocumentData } from 'firebase/firestore';
import type { NextPage } from 'next';
import Head from 'next/head';
import { DipsBarChart } from '../components';
import { database } from '../config/firebase';

import { useAuth } from '../hooks';

const Home: NextPage = () => {
  const [name, setName] = useState('');
  const [age, setAge] = useState('');
  const [info, setInfo] = useState<DocumentData | undefined>();
  const docRef = doc(database, 'CRUD Data', '1');
  const auth = getAuth();

  const { user } = useAuth();

  console.log('index - currentUser:', user);

  useEffect(() => {
    getData();
  }, []);

  const setData = async () => {
    const res = await setDoc(docRef, {
      name: name,
      age: Number(age)
    });

    setName('');
    setAge('');
    getData();
  };

  const getData = async () => {
    const res = await getDoc(docRef);

    setInfo(res.data());
  };

  // this should come from firebase
  const tickers = ['ABBV.VI', 'ALV.DE', 'BAS.DE', 'BMT.DE', 'SRB.F'];

  return (
    <>
      <Head>
        <title>Dip Finder</title>

        <meta name="description" content="Generated by create next app" />
        {/*<link rel="icon" href="/favicon.ico" />*/}
        <link rel="icon" type="image/svg+xml" href="/logo.svg" sizes="any" />
      </Head>

      <div>
        <h1>Home</h1>

        <input
          type="text"
          value={name}
          placeholder="Name"
          onChange={(e) => setName(e.target.value)}
        />
        <input
          type="number"
          value={age}
          placeholder="Age"
          onChange={(e) => setAge(e.target.value)}
        />
        <button onClick={setData}>Add</button>
        <p>Name: {info?.name}</p>
        <p>Age: {info?.age}</p>
        <button onClick={() => signOut(auth)}>sign out</button>
        <DipsBarChart tickers={tickers} />
      </div>
    </>
  );
};

export default Home;
